---
- hosts: all
  vars:
    brews:
      # Formulas
      bash:
      bash-completion:
      cloc:
      coreutils:
      curl:
      findutils:
      gcc:
      geoip:
      git: with-pcre2
      gnu-sed:
      gnu-tar:
      grep:
      hilite:
      imagemagick:
      java:
      jq:
      libffi:
      mercurial:
      minicom:
      mosh:
      netcat:
      nmap:
      node-build:
      nodenv:
      p7zip:
      pipenv:
      pstree:
      python:
      rbenv:
      ruby-build:
      rsync:
      sqlite:
      tree:
      watch:
      wget:
      z:

      # Casks
      - google-earth-pro
      - keepingyouawake
      - notion
      - steam
      - spotify
      - utc-menu-clock
      - visual-studio-code
      - zoom
    taps: []
    directories:
      - .ssh/sockets
      - code
    homefiles:
      config: .config
      bash_profile: .bash_profile
      bashrc: .bashrc
      inputrc: .inputrc
      rubocop.yml: .rubocop.yml
      Fonts: Library/Fonts
      vscode-settings.json: Library/Application Support/Code/User/settings.json
      vscode-keybindings.json: Library/Application Support/Code/User/keybindings.json
      clang-format: .clang-format
      ssh-config: .ssh/config
    node_modules:
      - eslint
      - eslint-plugin-react
    python_packages:
      - ipython
      - autopep8
      - flake8
      - coverage
      - pep8
      - pyflakes
      - pylint
      - virtualenvwrapper
    go_packages: []
    disable_hotkeys:
         60: "32, 49, 1048576"
         61: "32, 49, 1572864"
         80: "65535, 123, 393216"
         81: "65535, 124, 262144"
         82: "65535, 124, 393216"
         79: "65535, 123, 262144"
         32: "65535, 126, 262144"
         33: "65535, 125, 262144"
         34: "65535, 126, 393216"
         35: "65535, 125, 393216"
    user: "{{ lookup('env','USER') }}"
    home_dir: "{{ lookup('env','HOME') }}"
    gopath: "{{ home_dir }}/code/go"
    account_picture: sugar-glider.png
    backup_dir: "/Users/andrew/Drive/Apps/AppListBackup/"
  tasks:
    - import_tasks: tasks/files.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/preferences.yml
    - import_tasks: tasks/python.yml
    - import_tasks: tasks/go.yml
    - import_tasks: tasks/node.yml
