---
- hosts: all

  vars:
    applications:
      - android-studio
      - adium
      - dropbox
      - dash
      - evernote
      - firefox
      - gimp
      - google-chrome
      - google-earth
      - heroku-toolbelt
      - libreoffice
      - pacifist
      - pencil
      - slack
      - skype
      - spotify
      - textexpander
      - utc-menu-clock
      - utorrent
      - vmware-fusion
      - virtualbox
      - vlc
      - wireshark
      - xquartz
    application_dir: /Applications
    taps:
      - homebrew/dupes
      - homebrew/science
    brews:
      android-sdk:
      ant:
      awscli:
      bash-completion:
      cloc:
      curl:
      dfu-util:
      emacs: with-cocoa
      fasd:
      gcc:
      geoip: with-geoipupdate
      git: with-pcre
      gnu-sed: with-default-names
      gnu-tar: with-default-names
      grep: with-default-names
      hilite:
      hub:
      imagemagick:
      maven:
      mercurial:
      minicom:
      mobile-shell:
      mosquitto:
      netcat:
      nmap:
      node:
      octave:
      openssh: with-keychain-support,with-gssapi-support,with-brewed-openssl
      postgresql:
      python:
      rsync:
      sbt:
      scala:
      sqlite:
      unrar:
      watch:
      wget:
    directories:
      - .emacs_autosaves
      - .emacs_backups
      - .ssh/sockets
      - code
    homefiles:
      bash_profile: .bash_profile
      bashrc: .bashrc
      coffeelint-config.json: .coffeelint.json
      emacs: .emacs
      emacs.d: .emacs.d
      gitconfig: .gitconfig
      inputrc: .inputrc
      plugins.sbt: .sbt/0.13/plugins/plugins.sbt
      rubocop.yml: .rubocop.yml
      octaverc: .octaverc
      Fonts: Library/Fonts
      com.apple.Terminal.plist: Library/Preferences/com.apple.Terminal.plist
      gitignore: .gitignore
      Evoluent-VerticalMouseSettings.xml: "Library/Application Support/Evoluent/VerticalMouseSettings.xml"
    node_modules:
      - eslint
      - eslint-plugin-react
    python_packages:
      - ipython
      - autopep8
      - flake8
      - coverage
      - pep8
      - pyflakes
      - pylint
    go_packages:
      - github.com/nsf/gocode
      - github.com/dougm/goflymake
      - code.google.com/p/rog-go/exp/cmd/godef
    disable_hotkeys:
         60: "32, 49, 1048576"
         61: "32, 49, 1572864"
         80: "65535, 123, 393216"
         81: "65535, 124, 262144"
         82: "65535, 124, 393216"
         79: "65535, 123, 262144"
         32: "65535, 126, 262144"
         33: "65535, 125, 262144"
         34: "65535, 126, 393216"
         35: "65535, 125, 393216"
    home_dir: "{{ lookup('env','HOME') }}"
    gopath: "{{ home_dir }}/code/go"
    account_picture: sugar-glider.png
    backup_dir: "{{ inventory_dir }}/backups"
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/files.yml
    - include: tasks/preferences.yml
    - include: tasks/homebrew.yml
    - include: tasks/python.yml
    - include: tasks/go.yml
    - include: tasks/node.yml
