---
- hosts: all
  vars:
    applications:
      - android-studio
      - alfred
      - docker
      # No-go at Stripe anymore
      # - dropbox
      - dash3
      - deluge
      - emacs
      - evernote
      - firefox
      - gimp
      # - google-chrome Stripe orchestrates this
      - google-backup-and-sync
      - google-earth-pro
      - iterm2
      - libreoffice
      - pacifist
      - pencil
      # - slack Stripe orchestrates this
      - skype
      - spotify
      - utc-menu-clock
      - virtualbox
      - vlc
      - wireshark
      - xquartz
    application_dir: /Applications
    taps:
      - homebrew/dupes
      - homebrew/science
      - homebrew/services
      - caskroom/versions
    brews:
      awscli:
      bash:
      bash-completion:
      cloc:
      coreutils:
      curl:
      dfu-util:
      gcc:
      geoip: with-geoipupdate
      git: with-pcre2
      gnu-sed: --with-default-names
      gnu-tar: --with-default-names
      grep: --with-default-names
      hilite:
      hub:
      imagemagick:
      maven:
      mercurial:
      minicom:
      mobile-shell:
      netcat:
      nmap:
      node:
      octave:
      # Keychain support flags were removed at some point so prefer system SSH for now
      # openssh: with-keychain-support,with-gssapi-support,with-brewed-openssl
      parallel:
      p7zip:
      postgresql:
      pstree:
      python:
      rsync:
      sbt:
      scala:
      sqlite:
      unrar:
      watch:
      wget:
      z:
    directories:
      - .emacs_autosaves
      - .emacs_backups
      - .ssh/sockets
      - code
      - .config/git
    homefiles:
      bash_profile: .bash_profile
      bashrc: .bashrc
      emacs: .emacs
      emacs.d: .emacs.d
      gitconfig: .config/git/config
      inputrc: .inputrc
      rubocop.yml: .rubocop.yml
      Fonts: Library/Fonts
      gitignore: .config/git/ignore
      pep8: .config/pep8
      vscode-settings.json: Library/Application Support/Code/User/settings.json
    node_modules:
      - eslint
      - eslint-plugin-react
    python_packages:
      - ipython
      - autopep8
      - flake8
      - coverage
      - pep8
      - pyflakes
      - pylint
      - virtualenvwrapper
    go_packages:
      - github.com/nsf/gocode
      - github.com/dougm/goflymake
      - golang.org/x/tools/cmd/goimports
      - github.com/rogpeppe/godef
      - github.com/maruel/panicparse/cmd/pp
    disable_hotkeys:
         60: "32, 49, 1048576"
         61: "32, 49, 1572864"
         80: "65535, 123, 393216"
         81: "65535, 124, 262144"
         82: "65535, 124, 393216"
         79: "65535, 123, 262144"
         32: "65535, 126, 262144"
         33: "65535, 125, 262144"
         34: "65535, 126, 393216"
         35: "65535, 125, 393216"
    user: "{{ lookup('env','USER') }}"
    home_dir: "{{ lookup('env','HOME') }}"
    gopath: "{{ home_dir }}/code/go"
    account_picture: sugar-glider.png
    backup_dir: "{{ inventory_dir }}/backups"
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: tasks/files.yml
    - import_tasks: tasks/preferences.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/python.yml
    - import_tasks: tasks/go.yml
    - import_tasks: tasks/node.yml
