---
# - name: Check Homebrew is installed
#   stat: path=/opt/homebrew/bin/bash
#   register: brew_installed

# - name: Install Homebrew
#   shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
#   when: brew_installed.stat.exists == false

- name: Add homebrew taps
  shell: brew tap {{ item }}
  with_items: '{{taps}}'

- name: Update homebrew
  shell: brew update

- name: Install Homebrew libraries
  homebrew: name={{ item.key }} state=present install_options={{ item.value }}
  with_dict: '{{brews}}'
